### PR TITLE
refactor object and bucket count to fit odf_system

### PR DESCRIPTION
**Pull request by weirdwiz**
### Explain the changes
1.  Rename `job:noobaa_total_object_count:sum` to `odf_system_objects_total`
2.  Rename `job:noobaa_bucket_count:sum` to `odf_system_bucket_count`

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
LGTM

**Comment by liranmauda** [comment]
@weirdwiz Please tell me if we can merge it. then we should go and merge https://github.com/noobaa/noobaa-operator/pull/978

**Comment by nimrod-becker** [comment]
Wait, this will change existing integration, have we cleared with all those call sites?

**Comment by weirdwiz** [comment]
@liranmauda we can merge this, let me know if i need to change/remove the noobaa-operator PR

**Comment by liranmauda** [comment]
> Wait, this will change existing integration, have we cleared with all those call sites?

@weirdwiz ^^^
We will also wait for @nimrod-becker approval

**Comment by weirdwiz** [comment]
@nimrod-becker @liranmauda PTAL
I've updated the PR with adding the new metrics, instead of renaming.

**Comment by nimrod-becker** [comment]
LGTM

**Comment by nimrod-becker** [comment]
Reminder, we need to take thechanr and PR it into the noobaa-operator
@weirdwiz Can you take care of it, please? I see you already have a PR opened on the operator, lets just make sure its up to date

**Pull request merged**
